export class AptitudesDto {
  /*constructor(object: any) {
    this.str = object.str;
    this.agi = object.agi;

  };*/
  readonly swimm: number;
  readonly throw:number;
  readonly pull:number;
  readonly charge:number;
  readonly push:number;
  readonly equilibrium:number;
  readonly somersault:number;
  readonly jump:number;
  readonly climb:number;
  readonly scape:number;
  readonly flexibility:number;
  readonly lock:number;
  readonly searching:number;
  readonly scapology:number;
  readonly ride:number;
  readonly stealth:number;
  readonly hands:number;
  readonly rope:number;
  readonly mechanisms:number;
  readonly mountains:number;
  readonly intimidate:number;
  readonly weatherresist:number;
  readonly breath:number;
  readonly inmunity:number;
  readonly psicology:number;
  readonly decieve:number;
  readonly strategy:number;
  readonly generalculture:number;
  readonly criptography:number;
  readonly geography:number;
  readonly history:number;
  readonly legislation:number;
  readonly religion:number;
  readonly medicine:number;
  readonly apresial:number;
  readonly technologies:number;
  readonly magicitems:number;
  readonly spells:number;
  readonly sight:number;
  readonly hear:number;
  readonly smell:number;
  readonly cook:number;
  readonly empathy:number;
  readonly orientation:number;
  readonly smelldanger:number;
  readonly virtuosity:number;
  readonly faith:number;
  readonly bravery:number;
  readonly stiffness:number;
  readonly resilience:number;
  readonly selfcontrol:number;
  readonly patience:number;
  readonly leadership:number;
  readonly diplomacy:number;
  readonly performance:number;
  readonly seduce:number;
  readonly animaltreatment:number;
  readonly aesthetic:number;
  readonly cuteness:number;
  readonly coincidence:number;
  readonly games:number;
  readonly opportunism:number;
}